apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  PORT: MzAwMQ==
  JWT_TOKEN_SECRET: bmV3aW5EZXZvcHM=
  AWS_REGION: YXAtc291dGgtMQ==
  AWS_ACCESS_KEY_ID: <YOUR_AWS_ACCESS_ID>
  AWS_SECRET_ACCESS_KEY: <YOUR_AWS_SECRET_ACCESS_KEY>
  AWS_BUCKET_NAME: Y2Fwc3RvbmUtZWtz
  GITHUB_CLIENT_ID: T3YyM2xpc2ZneU9ESElPdkNISkw=
  GITHUB_CLIENT_SECRET: M2VjNDU3YzE4NGM3ZmJkYzdmZjE1ZGQzZWE3MTFlMWY3YjdiYWZjYg==